
#### `docker-compose.yml`
version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"  # Map backend port
    environment:
      - LIVEKIT_API_KEY=your_livekit_api_key
      - LIVEKIT_API_SECRET=your_livekit_api_secret
    volumes:
      - ./backend:/app  # Mount backend code for live updates

  frontend:
    build:
      context: ./frontend
    ports:
      - "8900:80"  # Map frontend port
    volumes:
      - ./frontend:/app  # Mount frontend code for live updates
