services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - LIVEKIT_API_KEY=your_livekit_api_key
      - LIVEKIT_API_SECRET=your_livekit_api_secret
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8900:80"
    environment:
      - NODE_ENV=production
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend