services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - LIVEKIT_API_KEY=your_livekit_api_key
      - LIVEKIT_API_SECRET=your_livekit_api_secret
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8900:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend