services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8900:80"
    environment:
      - NODE_ENV=production
      - VITE_LIVEKIT_URL=${LIVEKIT_URL}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  agent-worker:
    build:
      context: ./agent-worker
      dockerfile: Dockerfile
    environment:
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - LIVEKIT_URL=${LIVEKIT_URL}
    deploy:
      replicas: 2
    restart: unless-stopped
    depends_on:
      - backend