services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8900:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_LIVEKIT_URL=${REACT_APP_LIVEKIT_URL}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend